### ISSUE TITLE
[Bug] Inventory False Flag 

### ISSUE THREAD

**Issue by F3F5** [Photon-GitHub/AntiCheatAddition#644] opened 2024-05-26 14:30 UTC
![331897609-b63b0fb1-5697-4a88-9eef-7ba119b2c976](https://github.com/Photon-GitHub/AntiCheatAddition/assets/170719238/5cd0d4ae-3c7f-4fbd-b9fd-5f8fc145d2ae)

https://github.com/Photon-GitHub/AntiCheatAddition/assets/170719238/9e825c81-4f17-4c5a-bf50-8ce07b474dfc

[21:57:09 INFO]: [AntiCheatAddition] Version: 9.1.4

[21:57:14 INFO]: This server is running PandaSpigot version git-PandaSpigot-119 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT) (Git: 858ab0f)
[21:57:14 INFO]: Checking version, please wait...
[21:57:15 INFO]: You are running the latest version

**Comment by F3F5** [comment] 2024-05-26 14:30
![331897988-802f6100-ca4e-4fb8-a47d-8a4cb5d1d76b](https://github.com/Photon-GitHub/AntiCheatAddition/assets/170719238/48edd4f8-6ff5-430b-8671-9e475e191952)
![331897989-e8927f04-df35-45a0-8c60-95e77963e813](https://github.com/Photon-GitHub/AntiCheatAddition/assets/170719238/f374327a-92e0-462c-a73e-0deca65e2e7c)
Also, during the start of the match, the inventory was not even open

**Comment by Photon-GitHub** [comment] 2024-06-04 22:40
Your log shows that you reached 50 VL max. That is not exactly a lot, and if some player actually wants to provoke detections until they reach a serious VL, they would need at least a minute. I don't think I will fix that.

**Comment by F3F5** [comment] 2024-06-05 00:57
> Your log shows that you reached 50 VL max. That is not exactly a lot, and if some player actually wants to provoke detections until they reach a serious VL, they would need at least a minute. I don't think I will fix that.

i can't use inventory

**Comment by Photon-GitHub** [comment] 2024-06-08 17:49
Change the cancel_vl, it is configurable.

**Comment by Photon-GitHub** [comment] 2024-06-08 17:51
Anyways, this is a duplicate of #621

**Closed by Photon-GitHub** 2024-06-08 17:51 UTC
Labels: 1. bug, 3. unimportant
