### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by Regomy** [Photon-GitHub/AntiCheatAddition#571] opened 2023-09-30 17:23 UTC
1) https://gist.github.com/Regomy/5caeaee7932fa86273c97a65c5539713
2) https://gist.github.com/Regomy/5c4b1d1ab2b12fca13dcd54eca554d8e

**Comment by Photon-GitHub** [comment] 2023-10-01 20:53
Error 2 should be fixed in 8.8.3, the first error is caused by Duping SecretCache. I will look into it, you can disable that part for now.

**Comment by Photon-GitHub** [comment] 2023-10-05 19:47
Error 1 is caused by the getLocation method necessary for the check not being present in 1.8.8. I will make SecretCache autodisable on that version.

**Comment by Janmm14** [comment] 2023-10-05 23:36
> Error 1 is caused by the getLocation method necessary for the check not being present in 1.8.8. I will make SecretCache autodisable on that version.

earlier versions should have location method on the subinterfaces

**Closed** 2023-11-03 01:53 UTC
Labels: 1. error, 4. fixed
