### ISSUE TITLE
DamageIndicators module spam console with errors

### ISSUE THREAD

**Issue by Chevels** [Photon-GitHub/AntiCheatAddition#560] opened 2023-06-21 13:03 UTC
Hello,

I report here following the request of Photon on Spigot. I bought the plugin yesterday and here are the errors spamming my console:

Error 1 (related to DamageIndicators module):
[https://pastebin.com/qRZrs8b7](https://pastebin.com/qRZrs8b7)

Error 2 (very spammy !). I don't know what this error refers to:
[https://pastebin.com/yTzFebBw](https://pastebin.com/yTzFebBw)

**Server infos :**
This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)
You are running the latest version
Previous version: git-Paper-218 (MC: 1.19.2)

Protocollib : tested with latest release (5.0.0) and latest dev build (b654)

AntiCheatAddition : latest release [AntiCheatAddition] Version: 8.7.0

**Comment by Photon-GitHub** [comment] 2023-06-21 16:26
If there is not a special reason for using 1.19.2, you might want to try out 1.19.4. ProtocolLib has changed a lot of stuff internally between those two versions that might affect the errors. I generally only develop and provide support for the latest sub-version of minecraft (e.g. 1.18.2 or 1.19.4) because of changes like that. At some point I will also start enforcing 1.19.4.

**Comment by Chevels** [comment] 2023-06-21 16:48
The problem is that I have 82 plugins and some are not up to date beyond version 1.19.2... :/

**Comment by Photon-GitHub** [comment] 2023-06-21 17:00
Unless they also use ProtocolLib or use nms they will be compatible with 1.19.4. That is why they are plugins. Only if you actually need to interfere with the server or the protocol, you need to update every single version (and even I try to keep that stuff to a minimum to make updating ACA easier).

**Comment by Photon-GitHub** [comment] 2023-06-21 17:02
Does the error appear when you are alone on your server, just with mobs around or need to be at least two players present for the errors to appear?

**Comment by Chevels** [comment] 2023-06-22 17:46
I did not pay attention to this and as I have little availability this week I do not know when I will be able to test this. Don't bother, I've disabled the DamageIndicators module for now and will re-enable it when we go to 1.20 in a few months :)

If you want me to check anyway I will do it but with the end of the school year for the children and my IRL obligations I prefer not to promise a delay for several days.

Thank you for your reactivity in any case, it is appreciable ;)

**Comment by Photon-GitHub** [comment] 2023-06-22 19:47
Don’t worry. I regularly test with 1.20.1 and have not encountered those errors yet. So likely, they are caused by  using 1.19.2. If you don’t encounter the errors with DamageIndicators disabled, it should be fine.

**Comment by Photon-GitHub** [comment] 2023-10-05 19:42
I will close this for now, as 1.19.4 is now enforced and this should no longer happen. Feel free to reopen if you experience it again on newer versions.

**Closed by Photon-GitHub** 2023-10-05 19:42 UTC
Labels: 1. error
